
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AuthenticatedLogin", isSet = false )
    public class AuthenticatedLogin implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 256L 
		
	   )
	   
        @ASN1Element ( name = "clientUserData", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] clientUserData = null;
                
  
        @ASN1Element ( name = "avatar", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AvatarHash avatar = null;
                
  
        
        public byte[] getClientUserData () {
            return this.clientUserData;
        }

        

        public void setClientUserData (byte[] value) {
            this.clientUserData = value;
        }
        
  
        
        public AvatarHash getAvatar () {
            return this.avatar;
        }

        
        public boolean isAvatarPresent () {
            return this.avatar != null;
        }
        

        public void setAvatar (AvatarHash value) {
            this.avatar = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AuthenticatedLogin.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            