
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AvatarData", isSet = false )
    public class AvatarData implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 256L 
		
	   )
	   
        @ASN1Element ( name = "avatarBlock", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] avatarBlock = null;
                
  
        
        public byte[] getAvatarBlock () {
            return this.avatarBlock;
        }

        

        public void setAvatarBlock (byte[] value) {
            this.avatarBlock = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AvatarData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            