
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "DealFlopCardsMessage" )
    public class DealFlopCardsMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "DealFlopCardsMessage" , isSet = false )
       public static class DealFlopCardsMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "flopCard1", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Card flopCard1 = null;
                
  
        @ASN1Element ( name = "flopCard2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Card flopCard2 = null;
                
  
        @ASN1Element ( name = "flopCard3", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Card flopCard3 = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public Card getFlopCard1 () {
            return this.flopCard1;
        }

        

        public void setFlopCard1 (Card value) {
            this.flopCard1 = value;
        }
        
  
        
        public Card getFlopCard2 () {
            return this.flopCard2;
        }

        

        public void setFlopCard2 (Card value) {
            this.flopCard2 = value;
        }
        
  
        
        public Card getFlopCard3 () {
            return this.flopCard3;
        }

        

        public void setFlopCard3 (Card value) {
            this.flopCard3 = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_DealFlopCardsMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_DealFlopCardsMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(DealFlopCardsMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "DealFlopCardsMessage", isOptional =  false , hasTag =  true, tag = 28, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private DealFlopCardsMessageSequenceType  value;        

        
        
        public DealFlopCardsMessage () {
        }
        
        
        
        public void setValue(DealFlopCardsMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public DealFlopCardsMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DealFlopCardsMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            