
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "DealRiverCardMessage" )
    public class DealRiverCardMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "DealRiverCardMessage" , isSet = false )
       public static class DealRiverCardMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "riverCard", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Card riverCard = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public Card getRiverCard () {
            return this.riverCard;
        }

        

        public void setRiverCard (Card value) {
            this.riverCard = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_DealRiverCardMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_DealRiverCardMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(DealRiverCardMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "DealRiverCardMessage", isOptional =  false , hasTag =  true, tag = 30, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private DealRiverCardMessageSequenceType  value;        

        
        
        public DealRiverCardMessage () {
        }
        
        
        
        public void setValue(DealRiverCardMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public DealRiverCardMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DealRiverCardMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            