
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "DialogMessage" )
    public class DialogMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "DialogMessage" , isSet = false )
       public static class DialogMessageSequenceType implements IASN1PreparedElement {
                
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 128L 
		
	   )
	   
        @ASN1Element ( name = "notificationText", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String notificationText = null;
                
  
        
        public String getNotificationText () {
            return this.notificationText;
        }

        

        public void setNotificationText (String value) {
            this.notificationText = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_DialogMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_DialogMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(DialogMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "DialogMessage", isOptional =  false , hasTag =  true, tag = 131, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private DialogMessageSequenceType  value;        

        
        
        public DialogMessage () {
        }
        
        
        
        public void setValue(DialogMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public DialogMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DialogMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            