
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "EncryptedCards", isSet = false )
    public class EncryptedCards implements IASN1PreparedElement {
            @ASN1OctetString( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 16L, 
		
		max = 64L 
		
	   )
	   
        @ASN1Element ( name = "cardData", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private byte[] cardData = null;
                
  
        
        public byte[] getCardData () {
            return this.cardData;
        }

        

        public void setCardData (byte[] value) {
            this.cardData = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(EncryptedCards.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            