
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "EndKickPetitionMessage" )
    public class EndKickPetitionMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "EndKickPetitionMessage" , isSet = false )
       public static class EndKickPetitionMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "petitionId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId petitionId = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 9L 
		
	   )
	   
        @ASN1Element ( name = "numVotesAgainstKicking", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer numVotesAgainstKicking = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 9L 
		
	   )
	   
        @ASN1Element ( name = "numVotesInFavourOfKicking", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer numVotesInFavourOfKicking = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "resultPlayerKicked", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean resultPlayerKicked = null;
                
  

    @ASN1PreparedElement
    @ASN1Enum (
        name = "PetitionEndReasonEnumType"
    )
    public static class PetitionEndReasonEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "petitionEndEnoughVotes", hasTag = true , tag = 0 )
            petitionEndEnoughVotes , 
            @ASN1EnumItem ( name = "petitionEndTooFewPlayers", hasTag = true , tag = 1 )
            petitionEndTooFewPlayers , 
            @ASN1EnumItem ( name = "petitionEndPlayerLeft", hasTag = true , tag = 2 )
            petitionEndPlayerLeft , 
            @ASN1EnumItem ( name = "petitionEndTimeout", hasTag = true , tag = 3 )
            petitionEndTimeout , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PetitionEndReasonEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "petitionEndReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PetitionEndReasonEnumType petitionEndReason = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPetitionId () {
            return this.petitionId;
        }

        

        public void setPetitionId (NonZeroId value) {
            this.petitionId = value;
        }
        
  
        
        public Integer getNumVotesAgainstKicking () {
            return this.numVotesAgainstKicking;
        }

        

        public void setNumVotesAgainstKicking (Integer value) {
            this.numVotesAgainstKicking = value;
        }
        
  
        
        public Integer getNumVotesInFavourOfKicking () {
            return this.numVotesInFavourOfKicking;
        }

        

        public void setNumVotesInFavourOfKicking (Integer value) {
            this.numVotesInFavourOfKicking = value;
        }
        
  
        
        public Boolean getResultPlayerKicked () {
            return this.resultPlayerKicked;
        }

        

        public void setResultPlayerKicked (Boolean value) {
            this.resultPlayerKicked = value;
        }
        
  
        
        public PetitionEndReasonEnumType getPetitionEndReason () {
            return this.petitionEndReason;
        }

        

        public void setPetitionEndReason (PetitionEndReasonEnumType value) {
            this.petitionEndReason = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_EndKickPetitionMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_EndKickPetitionMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(EndKickPetitionMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "EndKickPetitionMessage", isOptional =  false , hasTag =  true, tag = 70, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private EndKickPetitionMessageSequenceType  value;        

        
        
        public EndKickPetitionMessage () {
        }
        
        
        
        public void setValue(EndKickPetitionMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public EndKickPetitionMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(EndKickPetitionMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            