
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "EndOfGameMessage" )
    public class EndOfGameMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "EndOfGameMessage" , isSet = false )
       public static class EndOfGameMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "winnerPlayerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId winnerPlayerId = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getWinnerPlayerId () {
            return this.winnerPlayerId;
        }

        

        public void setWinnerPlayerId (NonZeroId value) {
            this.winnerPlayerId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_EndOfGameMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_EndOfGameMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(EndOfGameMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "EndOfGameMessage", isOptional =  false , hasTag =  true, tag = 35, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private EndOfGameMessageSequenceType  value;        

        
        
        public EndOfGameMessage () {
        }
        
        
        
        public void setValue(EndOfGameMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public EndOfGameMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(EndOfGameMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            