
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "GameListUpdate", isSet = false )
    public class GameListUpdate implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gameMode", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetGameMode gameMode = null;
                
  
        
        public NetGameMode getGameMode () {
            return this.gameMode;
        }

        

        public void setGameMode (NetGameMode value) {
            this.gameMode = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GameListUpdate.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            