
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "GameListNew", isSet = false )
    public class GameListNew implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gameMode", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetGameMode gameMode = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "isPrivate", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean isPrivate = null;
                
  
@ASN1SequenceOf( name = "playerIds", isSetOf = false ) 

    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 10L 
		
	   )
	   
        @ASN1Element ( name = "playerIds", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<NonZeroId>  playerIds = null;
                
  
        @ASN1Element ( name = "adminPlayerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId adminPlayerId = null;
                
  
        @ASN1Element ( name = "gameInfo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetGameInfo gameInfo = null;
                
  
        
        public NetGameMode getGameMode () {
            return this.gameMode;
        }

        

        public void setGameMode (NetGameMode value) {
            this.gameMode = value;
        }
        
  
        
        public Boolean getIsPrivate () {
            return this.isPrivate;
        }

        

        public void setIsPrivate (Boolean value) {
            this.isPrivate = value;
        }
        
  
        
        public java.util.Collection<NonZeroId>  getPlayerIds () {
            return this.playerIds;
        }

        

        public void setPlayerIds (java.util.Collection<NonZeroId>  value) {
            this.playerIds = value;
        }
        
  
        
        public NonZeroId getAdminPlayerId () {
            return this.adminPlayerId;
        }

        

        public void setAdminPlayerId (NonZeroId value) {
            this.adminPlayerId = value;
        }
        
  
        
        public NetGameInfo getGameInfo () {
            return this.gameInfo;
        }

        

        public void setGameInfo (NetGameInfo value) {
            this.gameInfo = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GameListNew.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            