
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "GameListAdminChanged", isSet = false )
    public class GameListAdminChanged implements IASN1PreparedElement {
            
        @ASN1Element ( name = "newAdminPlayerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId newAdminPlayerId = null;
                
  
        
        public NonZeroId getNewAdminPlayerId () {
            return this.newAdminPlayerId;
        }

        

        public void setNewAdminPlayerId (NonZeroId value) {
            this.newAdminPlayerId = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GameListAdminChanged.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            