
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "InitialAmountOfMoney" )
    public class InitialAmountOfMoney implements IASN1PreparedElement {
    
            @ASN1Integer( name = "InitialAmountOfMoney" )
            @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 1000000L 
		
	   )
	   
            private Integer value;
            
            public InitialAmountOfMoney() {
            }

            public InitialAmountOfMoney(Integer value) {
                this.value = value;
            }
            
            public void setValue(Integer value) {
                this.value = value;
            }
            
            public Integer getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(InitialAmountOfMoney.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            