
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "InviteNotifyMessage" )
    public class InviteNotifyMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "InviteNotifyMessage" , isSet = false )
       public static class InviteNotifyMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "playerIdWho", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId playerIdWho = null;
                
  
        @ASN1Element ( name = "playerIdByWhom", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId playerIdByWhom = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPlayerIdWho () {
            return this.playerIdWho;
        }

        

        public void setPlayerIdWho (NonZeroId value) {
            this.playerIdWho = value;
        }
        
  
        
        public NonZeroId getPlayerIdByWhom () {
            return this.playerIdByWhom;
        }

        

        public void setPlayerIdByWhom (NonZeroId value) {
            this.playerIdByWhom = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_InviteNotifyMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_InviteNotifyMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(InviteNotifyMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "InviteNotifyMessage", isOptional =  false , hasTag =  true, tag = 17, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private InviteNotifyMessageSequenceType  value;        

        
        
        public InviteNotifyMessage () {
        }
        
        
        
        public void setValue(InviteNotifyMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public InviteNotifyMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(InviteNotifyMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            