
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "JoinGameReplyMessage" )
    public class JoinGameReplyMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "JoinGameReplyMessage" , isSet = false )
       public static class JoinGameReplyMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        
    @ASN1PreparedElement
    @ASN1Choice ( name = "joinGameResult" )
    public static class JoinGameResultChoiceType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "joinGameAck", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private JoinGameAck joinGameAck = null;
                
  
        @ASN1Element ( name = "joinGameFailed", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private JoinGameFailed joinGameFailed = null;
                
  
        
        public JoinGameAck getJoinGameAck () {
            return this.joinGameAck;
        }

        public boolean isJoinGameAckSelected () {
            return this.joinGameAck != null;
        }

        private void setJoinGameAck (JoinGameAck value) {
            this.joinGameAck = value;
        }

        
        public void selectJoinGameAck (JoinGameAck value) {
            this.joinGameAck = value;
            
                    setJoinGameFailed(null);
                            
        }

        
  
        
        public JoinGameFailed getJoinGameFailed () {
            return this.joinGameFailed;
        }

        public boolean isJoinGameFailedSelected () {
            return this.joinGameFailed != null;
        }

        private void setJoinGameFailed (JoinGameFailed value) {
            this.joinGameFailed = value;
        }

        
        public void selectJoinGameFailed (JoinGameFailed value) {
            this.joinGameFailed = value;
            
                    setJoinGameAck(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_JoinGameResultChoiceType;
        }

        private static IASN1PreparedElementData preparedData_JoinGameResultChoiceType = CoderFactory.getInstance().newPreparedElementData(JoinGameResultChoiceType.class);

    }

                
        @ASN1Element ( name = "joinGameResult", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private JoinGameResultChoiceType joinGameResult = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public JoinGameResultChoiceType getJoinGameResult () {
            return this.joinGameResult;
        }

        

        public void setJoinGameResult (JoinGameResultChoiceType value) {
            this.joinGameResult = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_JoinGameReplyMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_JoinGameReplyMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(JoinGameReplyMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "JoinGameReplyMessage", isOptional =  false , hasTag =  true, tag = 12, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private JoinGameReplyMessageSequenceType  value;        

        
        
        public JoinGameReplyMessage () {
        }
        
        
        
        public void setValue(JoinGameReplyMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public JoinGameReplyMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(JoinGameReplyMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            