
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "JoinNewGame", isSet = false )
    public class JoinNewGame implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gameInfo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetGameInfo gameInfo = null;
                
  
        
        public NetGameInfo getGameInfo () {
            return this.gameInfo;
        }

        

        public void setGameInfo (NetGameInfo value) {
            this.gameInfo = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(JoinNewGame.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            