
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "KickPetitionUpdateMessage" )
    public class KickPetitionUpdateMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "KickPetitionUpdateMessage" , isSet = false )
       public static class KickPetitionUpdateMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "petitionId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId petitionId = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 9L 
		
	   )
	   
        @ASN1Element ( name = "numVotesAgainstKicking", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer numVotesAgainstKicking = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 9L 
		
	   )
	   
        @ASN1Element ( name = "numVotesInFavourOfKicking", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer numVotesInFavourOfKicking = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 9L 
		
	   )
	   
        @ASN1Element ( name = "numVotesNeededToKick", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer numVotesNeededToKick = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPetitionId () {
            return this.petitionId;
        }

        

        public void setPetitionId (NonZeroId value) {
            this.petitionId = value;
        }
        
  
        
        public Integer getNumVotesAgainstKicking () {
            return this.numVotesAgainstKicking;
        }

        

        public void setNumVotesAgainstKicking (Integer value) {
            this.numVotesAgainstKicking = value;
        }
        
  
        
        public Integer getNumVotesInFavourOfKicking () {
            return this.numVotesInFavourOfKicking;
        }

        

        public void setNumVotesInFavourOfKicking (Integer value) {
            this.numVotesInFavourOfKicking = value;
        }
        
  
        
        public Integer getNumVotesNeededToKick () {
            return this.numVotesNeededToKick;
        }

        

        public void setNumVotesNeededToKick (Integer value) {
            this.numVotesNeededToKick = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_KickPetitionUpdateMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_KickPetitionUpdateMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(KickPetitionUpdateMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "KickPetitionUpdateMessage", isOptional =  false , hasTag =  true, tag = 69, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private KickPetitionUpdateMessageSequenceType  value;        

        
        
        public KickPetitionUpdateMessage () {
        }
        
        
        
        public void setValue(KickPetitionUpdateMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public KickPetitionUpdateMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(KickPetitionUpdateMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            