
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "KickPlayerRequestMessage" )
    public class KickPlayerRequestMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "KickPlayerRequestMessage" , isSet = false )
       public static class KickPlayerRequestMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "playerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId playerId = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPlayerId () {
            return this.playerId;
        }

        

        public void setPlayerId (NonZeroId value) {
            this.playerId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_KickPlayerRequestMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_KickPlayerRequestMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(KickPlayerRequestMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "KickPlayerRequestMessage", isOptional =  false , hasTag =  true, tag = 14, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private KickPlayerRequestMessageSequenceType  value;        

        
        
        public KickPlayerRequestMessage () {
        }
        
        
        
        public void setValue(KickPlayerRequestMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public KickPlayerRequestMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(KickPlayerRequestMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            