
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "MyActionRequestMessage" )
    public class MyActionRequestMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "MyActionRequestMessage" , isSet = false )
       public static class MyActionRequestMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "handNum", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId handNum = null;
                
  
        @ASN1Element ( name = "gameState", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetGameState gameState = null;
                
  
        @ASN1Element ( name = "myAction", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetPlayerAction myAction = null;
                
  
        @ASN1Element ( name = "myRelativeBet", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AmountOfMoney myRelativeBet = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getHandNum () {
            return this.handNum;
        }

        

        public void setHandNum (NonZeroId value) {
            this.handNum = value;
        }
        
  
        
        public NetGameState getGameState () {
            return this.gameState;
        }

        

        public void setGameState (NetGameState value) {
            this.gameState = value;
        }
        
  
        
        public NetPlayerAction getMyAction () {
            return this.myAction;
        }

        

        public void setMyAction (NetPlayerAction value) {
            this.myAction = value;
        }
        
  
        
        public AmountOfMoney getMyRelativeBet () {
            return this.myRelativeBet;
        }

        

        public void setMyRelativeBet (AmountOfMoney value) {
            this.myRelativeBet = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_MyActionRequestMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_MyActionRequestMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(MyActionRequestMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "MyActionRequestMessage", isOptional =  false , hasTag =  true, tag = 25, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private MyActionRequestMessageSequenceType  value;        

        
        
        public MyActionRequestMessage () {
        }
        
        
        
        public void setValue(MyActionRequestMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public MyActionRequestMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MyActionRequestMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            