
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "NetPlayerAction"
    )
    public class NetPlayerAction implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "actionNone", hasTag = true , tag = 0 )
            actionNone , 
            @ASN1EnumItem ( name = "actionFold", hasTag = true , tag = 1 )
            actionFold , 
            @ASN1EnumItem ( name = "actionCheck", hasTag = true , tag = 2 )
            actionCheck , 
            @ASN1EnumItem ( name = "actionCall", hasTag = true , tag = 3 )
            actionCall , 
            @ASN1EnumItem ( name = "actionBet", hasTag = true , tag = 4 )
            actionBet , 
            @ASN1EnumItem ( name = "actionRaise", hasTag = true , tag = 5 )
            actionRaise , 
            @ASN1EnumItem ( name = "actionAllIn", hasTag = true , tag = 6 )
            actionAllIn , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(NetPlayerAction.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            