
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "PlayersTurnMessage" )
    public class PlayersTurnMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "PlayersTurnMessage" , isSet = false )
       public static class PlayersTurnMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "playerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId playerId = null;
                
  
        @ASN1Element ( name = "gameState", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NetGameState gameState = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPlayerId () {
            return this.playerId;
        }

        

        public void setPlayerId (NonZeroId value) {
            this.playerId = value;
        }
        
  
        
        public NetGameState getGameState () {
            return this.gameState;
        }

        

        public void setGameState (NetGameState value) {
            this.gameState = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_PlayersTurnMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_PlayersTurnMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(PlayersTurnMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "PlayersTurnMessage", isOptional =  false , hasTag =  true, tag = 24, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private PlayersTurnMessageSequenceType  value;        

        
        
        public PlayersTurnMessage () {
        }
        
        
        
        public void setValue(PlayersTurnMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public PlayersTurnMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PlayersTurnMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            