
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "PlayerIdChangedMessage" )
    public class PlayerIdChangedMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "PlayerIdChangedMessage" , isSet = false )
       public static class PlayerIdChangedMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "oldPlayerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId oldPlayerId = null;
                
  
        @ASN1Element ( name = "newPlayerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId newPlayerId = null;
                
  
        
        public NonZeroId getOldPlayerId () {
            return this.oldPlayerId;
        }

        

        public void setOldPlayerId (NonZeroId value) {
            this.oldPlayerId = value;
        }
        
  
        
        public NonZeroId getNewPlayerId () {
            return this.newPlayerId;
        }

        

        public void setNewPlayerId (NonZeroId value) {
            this.newPlayerId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_PlayerIdChangedMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_PlayerIdChangedMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(PlayerIdChangedMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "PlayerIdChangedMessage", isOptional =  false , hasTag =  true, tag = 36, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private PlayerIdChangedMessageSequenceType  value;        

        
        
        public PlayerIdChangedMessage () {
        }
        
        
        
        public void setValue(PlayerIdChangedMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public PlayerIdChangedMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PlayerIdChangedMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            