
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PlayerAllIn", isSet = false )
    public class PlayerAllIn implements IASN1PreparedElement {
            
        @ASN1Element ( name = "playerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId playerId = null;
                
  
        @ASN1Element ( name = "allInCard1", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Card allInCard1 = null;
                
  
        @ASN1Element ( name = "allInCard2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Card allInCard2 = null;
                
  
        
        public NonZeroId getPlayerId () {
            return this.playerId;
        }

        

        public void setPlayerId (NonZeroId value) {
            this.playerId = value;
        }
        
  
        
        public Card getAllInCard1 () {
            return this.allInCard1;
        }

        

        public void setAllInCard1 (Card value) {
            this.allInCard1 = value;
        }
        
  
        
        public Card getAllInCard2 () {
            return this.allInCard2;
        }

        

        public void setAllInCard2 (Card value) {
            this.allInCard2 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PlayerAllIn.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            