
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;



        @ASN1Module ( name = "POKERTH_PROTOCOL", isImplicitTags =  false  ) 
        public class POKERTH_PROTOCOL {
        }
        