
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "RejectGameInvitationMessage" )
    public class RejectGameInvitationMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "RejectGameInvitationMessage" , isSet = false )
       public static class RejectGameInvitationMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "myRejectReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RejectGameInvReason myRejectReason = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public RejectGameInvReason getMyRejectReason () {
            return this.myRejectReason;
        }

        

        public void setMyRejectReason (RejectGameInvReason value) {
            this.myRejectReason = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_RejectGameInvitationMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_RejectGameInvitationMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(RejectGameInvitationMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "RejectGameInvitationMessage", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private RejectGameInvitationMessageSequenceType  value;        

        
        
        public RejectGameInvitationMessage () {
        }
        
        
        
        public void setValue(RejectGameInvitationMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public RejectGameInvitationMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RejectGameInvitationMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            