
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "RejectInvNotifyMessage" )
    public class RejectInvNotifyMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "RejectInvNotifyMessage" , isSet = false )
       public static class RejectInvNotifyMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "playerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId playerId = null;
                
  
        @ASN1Element ( name = "playerRejectReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RejectGameInvReason playerRejectReason = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPlayerId () {
            return this.playerId;
        }

        

        public void setPlayerId (NonZeroId value) {
            this.playerId = value;
        }
        
  
        
        public RejectGameInvReason getPlayerRejectReason () {
            return this.playerRejectReason;
        }

        

        public void setPlayerRejectReason (RejectGameInvReason value) {
            this.playerRejectReason = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_RejectInvNotifyMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_RejectInvNotifyMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(RejectInvNotifyMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "RejectInvNotifyMessage", isOptional =  false , hasTag =  true, tag = 19, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private RejectInvNotifyMessageSequenceType  value;        

        
        
        public RejectInvNotifyMessage () {
        }
        
        
        
        public void setValue(RejectInvNotifyMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public RejectInvNotifyMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RejectInvNotifyMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            