
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "RemovedFromGame", isSet = false )
    public class RemovedFromGame implements IASN1PreparedElement {
            

    @ASN1PreparedElement
    @ASN1Enum (
        name = "RemovedFromGameReasonEnumType"
    )
    public static class RemovedFromGameReasonEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "removedOnRequest", hasTag = true , tag = 0 )
            removedOnRequest , 
            @ASN1EnumItem ( name = "kickedFromGame", hasTag = true , tag = 1 )
            kickedFromGame , 
            @ASN1EnumItem ( name = "gameIsFull", hasTag = true , tag = 2 )
            gameIsFull , 
            @ASN1EnumItem ( name = "gameIsRunning", hasTag = true , tag = 3 )
            gameIsRunning , 
            @ASN1EnumItem ( name = "gameTimeout", hasTag = true , tag = 4 )
            gameTimeout , 
            @ASN1EnumItem ( name = "removedStartFailed", hasTag = true , tag = 5 )
            removedStartFailed , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RemovedFromGameReasonEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "removedFromGameReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RemovedFromGameReasonEnumType removedFromGameReason = null;
                
  
        
        public RemovedFromGameReasonEnumType getRemovedFromGameReason () {
            return this.removedFromGameReason;
        }

        

        public void setRemovedFromGameReason (RemovedFromGameReasonEnumType value) {
            this.removedFromGameReason = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RemovedFromGame.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            