
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ReportAvatarMessage" )
    public class ReportAvatarMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ReportAvatarMessage" , isSet = false )
       public static class ReportAvatarMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "reportedPlayerId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId reportedPlayerId = null;
                
  
        @ASN1Element ( name = "reportedAvatar", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private AvatarHash reportedAvatar = null;
                
  
        
        public NonZeroId getReportedPlayerId () {
            return this.reportedPlayerId;
        }

        

        public void setReportedPlayerId (NonZeroId value) {
            this.reportedPlayerId = value;
        }
        
  
        
        public AvatarHash getReportedAvatar () {
            return this.reportedAvatar;
        }

        

        public void setReportedAvatar (AvatarHash value) {
            this.reportedAvatar = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ReportAvatarMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ReportAvatarMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(ReportAvatarMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ReportAvatarMessage", isOptional =  false , hasTag =  true, tag = 135, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ReportAvatarMessageSequenceType  value;        

        
        
        public ReportAvatarMessage () {
        }
        
        
        
        public void setValue(ReportAvatarMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public ReportAvatarMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ReportAvatarMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            