
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ResetTimeoutMessage" )
    public class ResetTimeoutMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ResetTimeoutMessage" , isSet = false )
       public static class ResetTimeoutMessageSequenceType implements IASN1PreparedElement {
                
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ResetTimeoutMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ResetTimeoutMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(ResetTimeoutMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ResetTimeoutMessage", isOptional =  false , hasTag =  true, tag = 134, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ResetTimeoutMessageSequenceType  value;        

        
        
        public ResetTimeoutMessage () {
        }
        
        
        
        public void setValue(ResetTimeoutMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public ResetTimeoutMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ResetTimeoutMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            