
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ShowMyCardsRequestMessage" )
    public class ShowMyCardsRequestMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ShowMyCardsRequestMessage" , isSet = false )
       public static class ShowMyCardsRequestMessageSequenceType implements IASN1PreparedElement {
                
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ShowMyCardsRequestMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ShowMyCardsRequestMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(ShowMyCardsRequestMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ShowMyCardsRequestMessage", isOptional =  false , hasTag =  true, tag = 33, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private ShowMyCardsRequestMessageSequenceType  value;        

        
        
        public ShowMyCardsRequestMessage () {
        }
        
        
        
        public void setValue(ShowMyCardsRequestMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public ShowMyCardsRequestMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ShowMyCardsRequestMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            