
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "StartEventMessage" )
    public class StartEventMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "StartEventMessage" , isSet = false )
       public static class StartEventMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "fillWithComputerPlayers", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean fillWithComputerPlayers = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public Boolean getFillWithComputerPlayers () {
            return this.fillWithComputerPlayers;
        }

        

        public void setFillWithComputerPlayers (Boolean value) {
            this.fillWithComputerPlayers = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_StartEventMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_StartEventMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(StartEventMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "StartEventMessage", isOptional =  false , hasTag =  true, tag = 20, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private StartEventMessageSequenceType  value;        

        
        
        public StartEventMessage () {
        }
        
        
        
        public void setValue(StartEventMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public StartEventMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StartEventMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            