
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "StartEventAckMessage" )
    public class StartEventAckMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "StartEventAckMessage" , isSet = false )
       public static class StartEventAckMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_StartEventAckMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_StartEventAckMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(StartEventAckMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "StartEventAckMessage", isOptional =  false , hasTag =  true, tag = 21, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private StartEventAckMessageSequenceType  value;        

        
        
        public StartEventAckMessage () {
        }
        
        
        
        public void setValue(StartEventAckMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public StartEventAckMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StartEventAckMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            