
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "StartEvent", isSet = false )
    public class StartEvent implements IASN1PreparedElement {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "fillWithComputerPlayers", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean fillWithComputerPlayers = null;
                
  
        
        public Boolean getFillWithComputerPlayers () {
            return this.fillWithComputerPlayers;
        }

        

        public void setFillWithComputerPlayers (Boolean value) {
            this.fillWithComputerPlayers = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StartEvent.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            