
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "StatisticsData", isSet = false )
    public class StatisticsData implements IASN1PreparedElement {
            

    @ASN1PreparedElement
    @ASN1Enum (
        name = "StatisticsTypeEnumType"
    )
    public static class StatisticsTypeEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "statNumberOfPlayers", hasTag = true , tag = 1 )
            statNumberOfPlayers , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StatisticsTypeEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "statisticsType", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private StatisticsTypeEnumType statisticsType = null;
                
  @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "statisticsValue", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Long statisticsValue = null;
                
  
        
        public StatisticsTypeEnumType getStatisticsType () {
            return this.statisticsType;
        }

        

        public void setStatisticsType (StatisticsTypeEnumType value) {
            this.statisticsType = value;
        }
        
  
        
        public Long getStatisticsValue () {
            return this.statisticsValue;
        }

        

        public void setStatisticsValue (Long value) {
            this.statisticsValue = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StatisticsData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            