
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "StatisticsMessage" )
    public class StatisticsMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "StatisticsMessage" , isSet = false )
       public static class StatisticsMessageSequenceType implements IASN1PreparedElement {
                
@ASN1SequenceOf( name = "statisticsData", isSetOf = false ) 

    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 32L 
		
	   )
	   
        @ASN1Element ( name = "statisticsData", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private java.util.Collection<StatisticsData>  statisticsData = null;
                
  
        
        public java.util.Collection<StatisticsData>  getStatisticsData () {
            return this.statisticsData;
        }

        

        public void setStatisticsData (java.util.Collection<StatisticsData>  value) {
            this.statisticsData = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_StatisticsMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_StatisticsMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(StatisticsMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "StatisticsMessage", isOptional =  false , hasTag =  true, tag = 128, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private StatisticsMessageSequenceType  value;        

        
        
        public StatisticsMessage () {
        }
        
        
        
        public void setValue(StatisticsMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public StatisticsMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StatisticsMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            