
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TimeoutWarningMessage" )
    public class TimeoutWarningMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "TimeoutWarningMessage" , isSet = false )
       public static class TimeoutWarningMessageSequenceType implements IASN1PreparedElement {
                

    @ASN1PreparedElement
    @ASN1Enum (
        name = "TimeoutReasonEnumType"
    )
    public static class TimeoutReasonEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "timeoutNoDataReceived", hasTag = true , tag = 0 )
            timeoutNoDataReceived , 
            @ASN1EnumItem ( name = "timeoutInactiveGame", hasTag = true , tag = 1 )
            timeoutInactiveGame , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TimeoutReasonEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "timeoutReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TimeoutReasonEnumType timeoutReason = null;
                
  @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "remainingSeconds", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Long remainingSeconds = null;
                
  
        
        public TimeoutReasonEnumType getTimeoutReason () {
            return this.timeoutReason;
        }

        

        public void setTimeoutReason (TimeoutReasonEnumType value) {
            this.timeoutReason = value;
        }
        
  
        
        public Long getRemainingSeconds () {
            return this.remainingSeconds;
        }

        

        public void setRemainingSeconds (Long value) {
            this.remainingSeconds = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_TimeoutWarningMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_TimeoutWarningMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(TimeoutWarningMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "TimeoutWarningMessage", isOptional =  false , hasTag =  true, tag = 132, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TimeoutWarningMessageSequenceType  value;        

        
        
        public TimeoutWarningMessage () {
        }
        
        
        
        public void setValue(TimeoutWarningMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public TimeoutWarningMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TimeoutWarningMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            