
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Version", isSet = false )
    public class Version implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 65535L 
		
	   )
	   
        @ASN1Element ( name = "major", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer major = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 65535L 
		
	   )
	   
        @ASN1Element ( name = "minor", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer minor = null;
                
  
        
        public Integer getMajor () {
            return this.major;
        }

        

        public void setMajor (Integer value) {
            this.major = value;
        }
        
  
        
        public Integer getMinor () {
            return this.minor;
        }

        

        public void setMinor (Integer value) {
            this.minor = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Version.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            