
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "VoteKickRequestMessage" )
    public class VoteKickRequestMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "VoteKickRequestMessage" , isSet = false )
       public static class VoteKickRequestMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "petitionId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId petitionId = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "voteKick", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean voteKick = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPetitionId () {
            return this.petitionId;
        }

        

        public void setPetitionId (NonZeroId value) {
            this.petitionId = value;
        }
        
  
        
        public Boolean getVoteKick () {
            return this.voteKick;
        }

        

        public void setVoteKick (Boolean value) {
            this.voteKick = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_VoteKickRequestMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_VoteKickRequestMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(VoteKickRequestMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "VoteKickRequestMessage", isOptional =  false , hasTag =  true, tag = 67, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private VoteKickRequestMessageSequenceType  value;        

        
        
        public VoteKickRequestMessage () {
        }
        
        
        
        public void setValue(VoteKickRequestMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public VoteKickRequestMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(VoteKickRequestMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            