
package pokerth_protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "VoteKickReplyMessage" )
    public class VoteKickReplyMessage implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "VoteKickReplyMessage" , isSet = false )
       public static class VoteKickReplyMessageSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "gameId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId gameId = null;
                
  
        @ASN1Element ( name = "petitionId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NonZeroId petitionId = null;
                
  
        
    @ASN1PreparedElement
    @ASN1Choice ( name = "voteKickReplyType" )
    public static class VoteKickReplyTypeChoiceType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "voteKickAck", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private VoteKickAck voteKickAck = null;
                
  
        @ASN1Element ( name = "voteKickDenied", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private VoteKickDenied voteKickDenied = null;
                
  
        
        public VoteKickAck getVoteKickAck () {
            return this.voteKickAck;
        }

        public boolean isVoteKickAckSelected () {
            return this.voteKickAck != null;
        }

        private void setVoteKickAck (VoteKickAck value) {
            this.voteKickAck = value;
        }

        
        public void selectVoteKickAck (VoteKickAck value) {
            this.voteKickAck = value;
            
                    setVoteKickDenied(null);
                            
        }

        
  
        
        public VoteKickDenied getVoteKickDenied () {
            return this.voteKickDenied;
        }

        public boolean isVoteKickDeniedSelected () {
            return this.voteKickDenied != null;
        }

        private void setVoteKickDenied (VoteKickDenied value) {
            this.voteKickDenied = value;
        }

        
        public void selectVoteKickDenied (VoteKickDenied value) {
            this.voteKickDenied = value;
            
                    setVoteKickAck(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_VoteKickReplyTypeChoiceType;
        }

        private static IASN1PreparedElementData preparedData_VoteKickReplyTypeChoiceType = CoderFactory.getInstance().newPreparedElementData(VoteKickReplyTypeChoiceType.class);

    }

                
        @ASN1Element ( name = "voteKickReplyType", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private VoteKickReplyTypeChoiceType voteKickReplyType = null;
                
  
        
        public NonZeroId getGameId () {
            return this.gameId;
        }

        

        public void setGameId (NonZeroId value) {
            this.gameId = value;
        }
        
  
        
        public NonZeroId getPetitionId () {
            return this.petitionId;
        }

        

        public void setPetitionId (NonZeroId value) {
            this.petitionId = value;
        }
        
  
        
        public VoteKickReplyTypeChoiceType getVoteKickReplyType () {
            return this.voteKickReplyType;
        }

        

        public void setVoteKickReplyType (VoteKickReplyTypeChoiceType value) {
            this.voteKickReplyType = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_VoteKickReplyMessageSequenceType;
        }

       private static IASN1PreparedElementData preparedData_VoteKickReplyMessageSequenceType = CoderFactory.getInstance().newPreparedElementData(VoteKickReplyMessageSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "VoteKickReplyMessage", isOptional =  false , hasTag =  true, tag = 68, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private VoteKickReplyMessageSequenceType  value;        

        
        
        public VoteKickReplyMessage () {
        }
        
        
        
        public void setValue(VoteKickReplyMessageSequenceType value) {
            this.value = value;
        }
        
        
        
        public VoteKickReplyMessageSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(VoteKickReplyMessage.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            