# Macro to include arbitrary files in the QtCreator tree
#  when importing cmake
macro( qtcreator_add_project_resources resources )
    if(NOT DEFINED ${PROJECT_NAME}_NO_RESOURCE_PROJECTS)
        set(${PROJECT_NAME}_NO_RESOURCE_PROJECTS 0)
    else(NOT DEFINED ${PROJECT_NAME}_NO_RESOURCE_PROJECTS)
        MATH( EXPR ${PROJECT_NAME}_NO_RESOURCE_PROJECTS "${${PROJECT_NAME}_NO_RESOURCE_PROJECTS} + 1" )
    endif(NOT DEFINED ${PROJECT_NAME}_NO_RESOURCE_PROJECTS)
    set(m_resources ${ARGV})
    foreach(resource ${m_resources})
        if(IS_DIRECTORY ${resource})
            file(GLOB_RECURSE add_files ${resource}/*)
            set(m_resources2 ${m_resources2} ${add_files})
        elseif(EXISTS ${resource})
            set(m_resources2 ${m_resources2} ${resource})
        endif(IS_DIRECTORY ${resource})
    endforeach(resource ${ARGN})
    add_custom_target( ${PROJECT_NAME}_Resources${${PROJECT_NAME}_NO_RESOURCE_PROJECTS} ALL SOURCES ${m_resources2} )
endmacro()
